export const GET_JOBS_BEGIN = "GET_JOBS_BEGIN"
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS"
export const GET_JOBS_ERROR = "GET_JOBS_ERROR"

export const GET_SINGLE_JOB_BEGIN = "GET_SINGLE_JOB_BEGIN"
export const GET_SINGLE_JOB_SUCCESS = "GET_SINGLE_JOB_SUCCESS"
export const GET_SINGLE_JOB_ERROR = "GET_SINGLE_JOB_ERROR"

export const LOAD_JOBS = "LOAD_JOBS"
export const UPDATE_FILTERS = "UPDATE_FILTERS"
export const FILTER_JOBS = "FILTER_JOBS"
export const CLEAR_FILTERS = "CLEAR_FILTERS"

export const UPDATE_SORT = "UPDATE_SORT"
export const SORT_JOBS = "SORT_JOBS"